apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: connect4-server
  labels:
    app: connect4-server
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - "{{HOST}}"
    secretName: connect4-server-tls
  rules:
  - host: "{{HOST}}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: connect4-server
            port:
              number: 8000
